[package]
name = "simd"
version.workspace = true
edition.workspace = true

[dependencies]
half.workspace = true
simd_macros = { path = "../simd_macros" }
zerocopy.workspace = true

[dev-dependencies]
rand.workspace = true

[build-dependencies]
cc = "1.2.6"

[lints]
workspace = true
