[package]
name = "simd"
version.workspace = true
edition.workspace = true
publish = false

[features]
init = []

[dependencies]
simd_macros = { path = "../simd_macros" }

half.workspace = true
seq-macro.workspace = true
zerocopy.workspace = true

[dev-dependencies]
rand.workspace = true

[build-dependencies]
cc = "1.2.27"
which = "8.0.0"

[lints]
workspace = true
