[formatting]
indent_string = "    "

[[rule]]
keys = ["dependencies", "*-denpendencies", "lints", "patch.*", "profile.*"]

[rule.formatting]
reorder_keys = true
reorder_arrays = true
align_comments = true
