[package]
name = "vchord"
version = "0.0.0"
edition = "2021"

[lib]
name = "vchord"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_vchord"
path = "./src/bin/pgrx_embed.rs"

[features]
default = []
pg13 = ["pgrx/pg13", "pgrx-catalog/pg13"]
pg14 = ["pgrx/pg14", "pgrx-catalog/pg14"]
pg15 = ["pgrx/pg15", "pgrx-catalog/pg15"]
pg16 = ["pgrx/pg16", "pgrx-catalog/pg16"]
pg17 = ["pgrx/pg17", "pgrx-catalog/pg17"]

[dependencies]
base = { git = "https://github.com/tensorchord/pgvecto.rs.git", rev = "c911e8a476effaf05cd4b1a037826b100177bdad" }

# lock algebra version forever so that the QR decomposition never changes for same input
nalgebra = "=0.33.0"

# lock rkyv version forever so that data is always compatible
rkyv = { version = "=0.7.45", features = ["validation"] }

half = { version = "2.4.1", features = ["rkyv"] }
log = "0.4.22"
paste = "1"
pgrx = { version = "=0.12.8", default-features = false, features = ["cshim"] }
pgrx-catalog = "0.1.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
rayon = "1.10.0"
serde = "1"
toml = "0.8.19"
validator = { version = "0.18.1", features = ["derive"] }

[patch.crates-io]
half = { git = "https://github.com/tensorchord/half-rs.git" }

[lints]
rust.unsafe_op_in_unsafe_fn = "deny"
rust.unused_lifetimes = "warn"
rust.unused_qualifications = "warn"

[profile.opt]
debug-assertions = false
inherits = "dev"
opt-level = 3
overflow-checks = false

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
