[formatting]
indent_string = "    "

[[rule]]
include = ["**/Cargo.toml"]
keys = [
    "dependencies",
    "dev-dependencies",
    "build-dependencies",
    "target.*.dependencies",
    "lints",
    "workspace.dependencies",
    "workspace.lints",
]
formatting = { reorder_keys = true, reorder_arrays = true, align_comments = true }
