[package]
name = "vector"
version.workspace = true
edition.workspace = true

[dependencies]
distance = { path = "../distance" }
simd = { path = "../simd" }

half.workspace = true

[lints]
workspace = true
