[package]
name = "make"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
object = { version = "0.37.1", default-features = false, features = [
    "read",
    "wasm",
] }
target-triple = "0.1.4"
