[package]
name = "make"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
object = { version = "0.37.1", features = ["all"] }
target-triple = "0.1.4"
