name: Build pgrx Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'pgrx version'
        required: true
        type: string

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_NAME: "ghcr.io/tensorchord/vectorchord-pgrx"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/pgrx.Dockerfile
          push: true
          build-args: |
            PGRX_VERSION=${{ github.event.inputs.version }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}
