name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: "tag name (semver without v-prefix)"
        required: true
        type: string

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semver:
    runs-on: "ubuntu-latest"

    steps:
      - name: Semver
        id: semver
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ github.event.inputs.tag }}" || "${{ github.event.release.tag_name }}";
            console.log(`Tag: ${tag}`);
            const r = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/;
            if (!r.test(tag)) {
              core.setFailed(`Action failed with an invalid semver.`);
            }
            core.setOutput('SEMVER', tag);

    outputs:
      SEMVER: ${{ steps.semver.outputs.SEMVER }}

  build:
    needs: ["semver"]
    strategy:
      matrix:
        version: ["13", "14", "15", "16", "17", "18"]
        arch: ["x86_64", "aarch64"]
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-22.04' || 'ubuntu-22.04-arm' }}

    env:
      RUSTUP_AUTO_INSTALL: "0"
      RUSTFLAGS: "-Dwarnings"
      CARGO_TERM_COLOR: "always"
      RUST_BACKTRACE: "1"

    steps:
      - name: Set up Environment
        run: |
          sudo apt-get update

      - name: Install Rust
        run: rustup update

      - name: Install Clang
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm.sh | sudo bash -s -- 18
          sudo update-alternatives --install /usr/bin/clang clang $(which clang-18) 255

      - name: Install PostgreSQL
        run: |
          sudo apt-get remove -y '^postgres.*' '^libpq.*'
          sudo apt-get purge -y '^postgres.*' '^libpq.*'

          sudo apt-get install -y --no-install-recommends postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install -y --no-install-recommends postgresql-server-dev-${{ matrix.version }}

          pg_config

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          grep -q "default_version = '${{ needs.semver.outputs.SEMVER }}'" vchord.control || exit 1
          make build

      - name: Package (binary package)
        env:
          GH_TOKEN: ${{ github.token }}
          SEMVER: ${{ needs.semver.outputs.SEMVER }}
          VERSION: ${{ matrix.version }}
        run: |
          ARCH=$(uname -m)
          (cd ./build && zip -r ~/postgresql-${VERSION}-vchord_${SEMVER}_${ARCH}-linux-gnu.zip .)
          gh release upload --clobber $SEMVER ~/postgresql-${VERSION}-vchord_${SEMVER}_${ARCH}-linux-gnu.zip

      - name: Package (debian package)
        env:
          GH_TOKEN: ${{ github.token }}
          SEMVER: ${{ needs.semver.outputs.SEMVER }}
          VERSION: ${{ matrix.version }}
        run: |
          make DESTDIR="~/debian" install
          ARCH=$(uname -m)
          PLATFORM=$(dpkg --print-architecture)
          mkdir -p ~/debian/DEBIAN
          echo "Package: postgresql-${VERSION}-vchord
          Version: ${SEMVER}-1
          Depends: postgresql-${VERSION}, libgcc-s1, libc6 (>= 2.35)
          Section: database
          Priority: optional
          Architecture: ${PLATFORM}
          Maintainer: Tensorchord <support@tensorchord.ai>
          Description: Vector database plugin for Postgres, written in Rust, specifically designed for LLM
          Homepage: https://vectorchord.ai/
          License: AGPL-3.0-only or Elastic-2.0" \
          > ~/debian/DEBIAN/control
          (cd ~/debian && find usr -type f -print0 | xargs -0 md5sum) > ~/debian/DEBIAN/md5sums
          dpkg-deb --root-owner-group -Zxz --build ~/debian ~/postgresql-${VERSION}-vchord_${SEMVER}-1_${PLATFORM}.deb
          gh release upload --clobber $SEMVER ~/postgresql-${VERSION}-vchord_${SEMVER}-1_${PLATFORM}.deb

  pgxn:
    runs-on: "ubuntu-latest"
    needs: ["semver", "build"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload
        env:
          SEMVER: ${{ needs.semver.outputs.SEMVER }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: |
          mkdir -p ./build

          sed -e "s/@DISTVERSION@/${SEMVER}/g" META.json.in > META.json
          git archive --format zip --prefix "vchord-${SEMVER}/" --add-file META.json -o "./build/vchord--${SEMVER}.zip" HEAD

          curl --fail -sS \
            --user "tensorchord:${PGXN_PASSWORD}" \
            -F "submit=Release It!" \
            -F "archive=@./build/vchord--${SEMVER}.zip" \
            -H "X-Requested-With: XMLHttpRequest" \
            https://manager.pgxn.org/upload
